resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- cluster_role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- pflacpmonitor_editor_role.yaml
- pflacpmonitor_viewer_role.yaml
- operand
