---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: operator-allow-egress-to-api-server
  namespace: system
spec:
  podSelector:
    matchLabels:
      control-plane: controller-manager
  egress:
    - ports:
        - protocol: TCP
          port: 6443
  policyTypes:
    - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: operator-allow-to-dns
  namespace: system
spec:
  podSelector:
    matchLabels:
      control-plane: controller-manager
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-dns
          podSelector:
            matchLabels:
              dns.operator.openshift.io/daemonset-dns: default
      ports:
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 53
  policyTypes:
    - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: operator-allow-from-api-server-to-webhook
  namespace: system
spec:
  podSelector:
    matchLabels:
      control-plane: controller-manager
  ingress:
    - ports:
        - protocol: TCP
          port: 9443
  policyTypes:
    - Ingress
